# Generated by Django 3.2 on 2021-05-18 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=7, verbose_name='جنسیت')),
                ('height', models.IntegerField(verbose_name='قد')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('WBC', models.FloatField()),
                ('RBC', models.FloatField()),
                ('Hemoglobin', models.FloatField()),
                ('Hematocrit', models.FloatField()),
                ('MCV', models.FloatField()),
                ('MPV', models.FloatField()),
                ('MCH', models.FloatField()),
                ('MCHC', models.FloatField()),
                ('RDWCV', models.FloatField()),
                ('Platelets', models.FloatField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'آزمایش CBC',
                'verbose_name_plural': 'آزمایش CBC',
            },
        ),
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('ventRate', models.IntegerField()),
                ('PR', models.IntegerField()),
                ('Pms', models.IntegerField()),
                ('QRSms', models.IntegerField()),
                ('Tms', models.IntegerField()),
                ('QTms', models.IntegerField()),
                ('QTCms', models.IntegerField()),
                ('Pdeg', models.IntegerField()),
                ('QRSdeg', models.IntegerField()),
                ('Tdeg', models.IntegerField()),
                ('RV1mv', models.FloatField()),
                ('SV5mv', models.FloatField()),
                ('RV5mv', models.FloatField()),
                ('SV1mv', models.FloatField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'نتیجه ECG',
                'verbose_name_plural': 'نتایج ECG',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('name', models.CharField(max_length=128, verbose_name='نام و نام خانوادگی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=7, verbose_name='جنسیت')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='HeartAttack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('probability', models.CharField(choices=[('احتمال حمله قلبی بالاست', 'احتمال حمله قلبی بالاست'), ('احتمال حمله قلبی پایین است', 'احتمال حمله قلبی پایین است')], max_length=128, verbose_name='تشخیص حمله قلبی')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ecg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.ecg', verbose_name='نام بیمار')),
            ],
            options={
                'verbose_name': 'احتمال حمله قلبی',
                'verbose_name_plural': 'تشخیص حمله قلبی',
            },
        ),
        migrations.AddField(
            model_name='ecg',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='نام بیمار'),
        ),
    ]
